class UikitInit < Formula
  desc "Scratch UIKit iOS app with programmatic UI, generated by Xcode's template engine"
  homepage "https://github.com/Cyanosite/uikit-init"
  url "https://github.com/Cyanosite/uikit-init/archive/refs/tags/v0.2.0.tar.gz"
  # After tagging a release: curl -L <url> | shasum -a 256
  sha256 "0e0b63d13159031372eb4fb8ec8b216c1c01541372a91636b08e10a6d9a75701"
  license "MIT"
  head "https://github.com/Cyanosite/uikit-init.git", branch: "main"

  depends_on xcode: ["26.3", :build]
  depends_on :macos

  def install
    # SwiftPM's own sandbox conflicts with Homebrew's build sandbox.
    system "swift", "build", "--disable-sandbox", "-c", "release"
    bin.install ".build/release/uikit-init"
  end

  def caveats
    <<~EOS
      uikit-init talks to Xcode through `xcrun mcpbridge`, so Xcode 26.3+ must have
      MCP enabled: Xcode › Settings › Intelligence › Model Context Protocol, or
      `sudo xcrun mcp-server enable` for headless use.

      Xcode approves MCP clients per binary for 24 hours, so the first run after
      each install or upgrade shows an approval prompt.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/uikit-init --version")
    assert_match "programmatic UI", shell_output("#{bin}/uikit-init --help")
  end
end
